# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create streams

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create broadcasts
      env:
          CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          DISCORD_WEBHOOK_SUCCESS: ${{ secrets.DISCORD_WEBHOOK_STREAMS }}
          DISCORD_WEBHOOK_FAILURE: ${{ secrets.DISCORD_WEBHOOK_FAILURE }}
      run: |
        python create_broadcasts.py
