name: Pushing Google App Scripts
- uses: daikikatsuragawa/clasp-action@v1.1.0
  with:
    accessToken: ${{ secrets.ACCESS_TOKEN }}
    idToken: ${{ secrets.ID_TOKEN }}
    refreshToken: ${{ secrets.REFRESH_TOKEN }}
    clientId: ${{ secrets.CLIENT_ID }}
    clientSecret: ${{ secrets.CLIENT_SECRET }}
    scriptId: ${{ secrets.SCRIPT_ID }}
    rootDir: google_apps/signup_tools
    command: 'push'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
